# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "Koo Lab"
title:              "Advancing AI for Genomics"
description:        ""


# URL
url:                http://koo-lab.github.io
plugins:
   - jekyll-sitemap

baseurl:
#baseurl:            "" #For Root Domain
permalink:          /:year/:month/:day/:title.html

# Markdown
markdown:           kramdown

# Highlighter
highlighter:        rouge

# Navigation
nav:
  - name:           "Home"
    href:           "/"
  - name:           "Research"
    href:           "/Research"
  - name:           "People"
    href:           "/People"
  - name:           "Publications"
    href:           "/Publication"
  - name:           "Openings"
    href:           "/Openings"
  - name:           "Social"
    href:           "/Social"
  - name:           "Contact"
    href:           "/Contact"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"
  -
    scope:
      path:         ""
      type:         "people"
    values:
      layout:       "profile"


collections:
  people:
    output: true
    permalink: /people/:title/index.html
    
plugins:
   - jekyll-sitemap
